name: pigeon_generator
version: 3.1.0
description: Integrate build_runner with pigeon code generation to automate the process of generating platform channels.
homepage: https://github.com/melvinotieno/pigeon_generator
repository: https://github.com/melvinotieno/pigeon_generator
issue_tracker: https://github.com/melvinotieno/pigeon_generator/issues
documentation: https://github.com/melvinotieno/pigeon_generator/blob/main/README.md

topics:
  - build-runner
  - pigeon
  - pigeon-generator
  - pigeon-build-runner

environment:
  sdk: ^3.7.0

dependencies:
  build: ^4.0.2
  meta: ^1.17.0
  path: ^1.9.1
  pigeon: ^26.1.0
  scratch_space: ^1.2.0
  yaml: ^3.1.3

dev_dependencies:
  build_test: ^3.5.3
  lints: ^6.0.0
  test: ^1.26.3
